version: '3'
services:
  db:
    image: mysql:5.7.19
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: leverage
      MYSQL_USER: leverage
      MYSQL_PASSWORD: leverage
    volumes:
      - ./volumes/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5220:3306
  api:
    image: leverage-api:latest
    build: ./images/api
    ports:
      - 5221:5000
    links:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - 5222:80
    links:
      - db
